### ISSUE TITLE
A way to delay a slot refresh and disabling auto-refresh

### ISSUE THREAD

**Issue by haloflooder** [ClubObsidian/DynamicGui#111]
Would be useful if there was a way to delay a slot refresh by ticks.

A good example would be setting an slot's icon/name/lore/etc for "You don't have enough money!" on click then reverting back to the original slot state after an set amount of ticks.

Currently can't do it with the current animation system since it can just instantly revert or skip a frame on click based on the slot's current frame/tick.

A clean solution would probably be adding a function "setticks" to set the tick for the slot.

Auto refresh is also not necessary for many slots we have and it's just wasted performance for having to go through replacers for a slot everytime it auto refreshes. Since refreshing has mostly been used to reset a slot once after a click.

**Comment by virustotalop** [comment]
@haloflooder 
```
Would be useful if there was a way to delay a slot refresh by ticks.

A good example would be setting an slot's icon/name/lore/etc for "You don't have enough money!" on click then reverting back to the original slot state after an set amount of ticks.
```
I think this can already be done? Let me know if we still need something else.

```
Auto refresh is also not necessary for many slots we have and it's just wasted performance for having to go through replacers for a slot everytime it auto refreshes. Since refreshing has mostly been used to reset a slot once after a click.
```
Slots don't auto-refresh unless they are defined to do so, unless I am missing something.

**Comment by haloflooder** [comment]
There currently isn't a way to refresh a slot with a delay after the player clicked the slot.

For example, can't do something like this afaik.

- Player click slot
- Slot renames to "Not available!"
- Wait 20 ticks
- Slot refreshes because player clicked slot and waited for delay to finish.

Having a `delayedrefresh` function would be nice if we don't want the slot to constantly refresh on it's own and only refresh after a certain amount of ticks triggered by a click event.
