### ISSUE TITLE
Moveable slots

### ISSUE THREAD

**Issue by virustotalop** [ClubObsidian/DynamicGui#136]
Make it so that slots can have items moved into them. Maybe icon should be ignored for a slot that is moveable. Below is a possible format of how moveable slots should work.
```yaml
19:
  moveable: true
```

Moveable slots should also have functions related to them. They should probably be able to check material type, name, lore and custom nbt. Anything else you think that would be needed?

**Comment by DanHues** [comment]
anything that pertains to the item, 
name, lore, nbt, data value, line or lore?, material type. im assuming intractable slots would be a different thing entirely, i.e removing one slot to another slot within the gui

**Comment by virustotalop** [comment]
This would be used for crafting recipes, consumables etc. @DanHues

**Comment by DanHues** [comment]
oh okay cool, at its simplest in a single slot it would be fine, but there would need to be some way to cross reference multiple slots to do something like a crafting recipe. i.e slot 1 has a stick and slot 2 has a carrot. the slot to give the player the item would need to somehow be able to reference those slots to give the correct item
