### ISSUE TITLE
Async functions

### ISSUE THREAD

**Issue by virustotalop** [ClubObsidian/DynamicGui#219]
TODO:
- [x] Implement async functions
- [x] If the player logs off operations can not complete as intended, for example items added to the user when they are logged off will not save
- [x] Interaction with the gui is still possible and could lead to unintended consequences
- [x] Other guis could still be opened

There are probably other things that need to be though of what but I can't think of anything right now. What do you think @haloflooder @lrmtheboss

**Comment by lrmtheboss** [comment]
I can't think of any others at the moment.

On interactions with the GUI, it should give an error message like "Please wait for the previous action to complete"
Once a function is complete the player should get a message such as "Some action has completed successfully"

**Comment by virustotalop** [comment]
Seems to be working so far

![async](https://i.imgur.com/Sgyh0Id.gif)
