### ISSUE TITLE
[Addition] Messages.yml

### ISSUE THREAD

**Issue by lrmtheboss** [ClubObsidian/DynamicGui#220]
Add messages.yml to hold predefined messages used in functions and allow the user to change them as they want
Could use the same file or another one to allow users to add custom additional messages for uses in functions/guis where such messages will be used many times over

**Comment by virustotalop** [comment]
Macros can probably be used for this. Is there any reason why macros couldn't be used? I don't think macros are a documented feature currently, need to start re-writing those docs soon.

Example of macros
```yaml
'rank-permission-base':
  '%rankpermission-base%': "ranks."
  ```
This would then be added to a macro file. Then `%rankpermission-base%` can be used as a replacer in the gui.

**Comment by lrmtheboss** [comment]
Yea I've never used nor understand how to use the Marcos, it would be great to them documented

**Comment by lrmtheboss** [comment]
I have made some simple documentation off what you said here https://dynamicgui.lrmtheboss.com/macros
