### ISSUE TITLE
Sponge inventory itemstacks cannot be retrieved via index [$50]

### ISSUE THREAD

**Issue by virustotalop** [ClubObsidian/DynamicGui#28]
Having issues retrieving itemstacks via index.

**Comment by virustotalop** [comment]
Partially implemented in ec629387b081bc6fb274147139358142d73e729b InventoryWrapper should handle ItemStackWrappers internally instead of relying on native inventory types. Settype functions etc that rely on retrieving the itemstack from the inventory are broken currently.

**Comment by virustotalop** [comment]
Inventories do not update on sponge, still needs to be investigated for set functions.

**Comment by TridiumX** [comment]
Inventories update fine. But slots are reverted by sponge when click events are cancelled. This is not ideal, since it overrides any changes made to the clicked slot. This can be avoided however by removing slot change logic from the scope, using a task and delaying for 1ms.

**Comment by virustotalop** [comment]
@TridiumX Start working on the issue on the bountysource so we can award the bounty to you.
