### ISSUE TITLE
Issues with NBT Tags & Loading newer plugin versions

### ISSUE THREAD

**Issue by FMS25** [ClubObsidian/DynamicGui#286]
Hi, 

Issue number one is I am struggling to add NBT data to player heads for my GUI. For example:

```
"28":
  icon: "PLAYER_HEAD"
  name: "Pets"
  lore:
  - "&8&m--------&3&m--------------&8&m--------"
  - "&7"
  - "&b&lRedeem your Pets!"
  - "&7"
  - "&fEarned pets through rewards?"
  - "&fRedeem them by clicking here"
  - "&fto load up the Pets GUI"
  - "&7"
  - "&6Enjoy your new little friend"
  - "&8&m--------&3&m--------------&8&m--------"
  functions:
    load:
      type:
      - load
      functions:
      - "setnbt: {SkullOwner:\"Notch\"}"
    click:
      type:
      - click
      functions:
      - "executep: mpet open"
```
It gives me the console error:

13.11 18:05:46 [Server] [WARN] java.lang.NoSuchMethodException: net.minecraft.world.item.ItemStack.setTag(net.minecraft.nbt.NBTTagCompound)
13.11 18:05:46 [Server] [WARN] at java.base/java.lang.Class.getDeclaredMethod(Class.java:2648)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.util.bukkit.BukkitNBTUtil.setTag(BukkitNBTUtil.java:107)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.inventory.bukkit.BukkitItemStackWrapper.setNBT(BukkitItemStackWrapper.java:198)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.function.impl.SetNBTFunction.function(SetNBTFunction.java:48)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.util.FunctionUtil.runFunctionData(FunctionUtil.java:90)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.util.FunctionUtil.recurFunctionNodes(FunctionUtil.java:47)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.util.FunctionUtil.tryFunctions(FunctionUtil.java:38)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.manager.dynamicgui.GuiManager.openGui(GuiManager.java:202)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.manager.dynamicgui.GuiManager.openGui(GuiManager.java:168)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.manager.dynamicgui.GuiManager.openGui(GuiManager.java:164)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.command.bukkit.CustomCommandExecutor.onCommand(CustomCommandExecutor.java:40)
13.11 18:05:46 [Server] [WARN] at DynamicGui-4.1.0-b40.jar//com.clubobsidian.dynamicgui.command.bukkit.CustomCommand.execute(CustomCommand.java:32)
13.11 18:05:46 [Server] [WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
13.11 18:05:46 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2537)
13.11 18:05:46 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.chat(CraftPlayer.java:706)
13.11 18:05:46 [Server] [WARN] at DeluxeHub-3.5.2.jar//fun.lewisdev.deluxehub.action.actions.CommandAction.execute(CommandAction.java:16)
13.11 18:05:46 [Server] [WARN] at DeluxeHub-3.5.2.jar//fun.lewisdev.deluxehub.action.ActionManager.lambda$executeActions$1(ActionManager.java:55)
13.11 18:05:46 [Server] [WARN] at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
13.11 18:05:46 [Server] [WARN] at DeluxeHub-3.5.2.jar//fun.lewisdev.deluxehub.action.ActionManager.executeActions(ActionManager.java:47)
13.11 18:05:46 [Server] [WARN] at DeluxeHub-3.5.2.jar//fun.lewisdev.deluxehub.module.modules.hotbar.items.CustomItem.onInteract(CustomItem.java:22)
13.11 18:05:46 [Server] [WARN] at DeluxeHub-3.5.2.jar//fun.lewisdev.deluxehub.module.modules.hotbar.HotbarItem.hotbarItemInteract(HotbarItem.java:129)
13.11 18:05:46 [Server] [WARN] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source)
13.11 18:05:46 [Server] [WARN] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
13.11 18:05:46 [Server] [WARN] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
13.11 18:05:46 [Server] [WARN] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
13.11 18:05:46 [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
13.11 18:05:46 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545)
13.11 18:05:46 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502)
13.11 18:05:46 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497)
13.11 18:05:46 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492)
13.11 18:05:46 [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:488)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2026)
13.11 18:05:46 [Server] [WARN] at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32)
13.11 18:05:46 [Server] [WARN] at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
13.11 18:05:46 [Server] [WARN] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.TickTask.run(TickTask.java:18)
13.11 18:05:46 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
13.11 18:05:46 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
13.11 18:05:46 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
13.11 18:05:46 [Server] [WARN] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1289)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1177)
13.11 18:05:46 [Server] [WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
13.11 18:05:46 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:831)
13.11 18:05:46 [Server] [ERROR] null.

My Second issue is any build above 40 on the jenkins gives me the error:

[17:54:11] [Server thread/ERROR]: Could not load 'plugins/DynamicGui-5.0.1-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.2.jar:git-Paper-246]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.2.jar:git-Paper-246]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-246]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-246]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

Please could you help me resolve this?

FMS

**Comment by virustotalop** [comment]
@FMS25 In yaml files you need to escape double quotes. So this `"setnbt: {SkullOwner:"Notch"}"` needs to be `"setnbt: {SkullOwner:\"Notch\"}"`

**Comment by FMS25** [comment]
Sweet, Thank you, so I have gotten that working, a couple more questions if I may:

How do I add custom textures to the NBT tag rather than of just the skull owner's name? Eg a head like this:

https://minecraft-heads.com/custom-heads/decoration/46946-diamond-chest

I am also on another part of the config I have this:

"36":
  icon: "RECOVERY_COMPASS"
  setenchants: DURABILITY,1
  name: "Our Webstore"
  
  I want to be able to hide the enchant so it doesn't show in the GUI, how would I do that?

**Comment by virustotalop** [comment]
If you just want the slot to glow you can just use `glow: true` For minecraft heads it depends on the version but you would use `nbt: yournbtgoeshere` in the slot or `setnbt` as a function like you did before. So for that given example and assuming 1.16+ it should be something like this `nbt: "[{display:{SkullOwner:{Id:[I;-1938086820,2026588190,-1123594741,2095845784],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzFmN2NkZmVhMmQyMWNkNWY2ZWJiZjQ4NDgxNzYxYzZjYmRmMzZkMDBmZTY0MDgzNjg2ZTlhZWFhM2YxZjIxNyJ9fX0="}]}}}](nbt: {display:{SkullOwner:{Id:[I;-1938086820,2026588190,-1123594741,2095845784],Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzFmN2NkZmVhMmQyMWNkNWY2ZWJiZjQ4NDgxNzYxYzZjYmRmMzZkMDBmZTY0MDgzNjg2ZTlhZWFhM2YxZjIxNyJ9fX0=\"}]}}})"`

Just make sure that you escape all double quotes with a backslash so instead of just `"` make all double quotes `\"`

If you have any other questions you can also add me on discord if you want `virustotal#0001`

**Comment by haloflooder** [comment]
Protip: You can also use ' instead of " with strings which is what I personally like to do with NBT's

So instead of 
```
"setnbt: {SkullOwner:\"Notch\"}"
```
you can do 
```
'setnbt: {SkullOwner:"Notch"}'
```
