### ISSUE TITLE
[Feature Request] Add API for use by other plugins

### ISSUE THREAD

**Issue by lrmtheboss** [ClubObsidian/DynamicGui#287]
Add an API for use by other plugins to create, open, edit, and delete GUIs on the fly
Only allow deletion of GUIs that were made through the API
GUIs will go away upon server restart or plugin reload 
- will need a call/event to re-add these GUIs if they get removed upon plugging reload

Uses
- instead of having to write your own code to deal with GUIs, you can use dynamic GUI to do it for you
- you could have base GUI files stored in the GUIs folder and then let another plugin edit them and open them example a menu for another controlling a plugin whose info varies from player to player, that plugin could provide its own functions with callbacks to do what it needs to do

**Comment by haloflooder** [comment]
There is already an API for you to do whatever with GUI's

This is what you would use to build custom functions, gui's, etc
https://github.com/ClubObsidian/DynamicGui/tree/master/core/src/main/java/com/clubobsidian/dynamicgui/core/builder

This is what you can use to open gui's and do other things with it.
https://github.com/ClubObsidian/DynamicGui/blob/master/core/src/main/java/com/clubobsidian/dynamicgui/core/manager/dynamicgui/GuiManager.java

Is there anything else you're looking for? Can pretty much do whatever with the current tools we provide.

The GUI's handled by 3rd party plugins are not handled by us in terms of base GUI files and whatnot. That's up to the plugin developer at that point. It makes more sense for the base GUI's to be in the plugin's folder rather then the dynamic gui folder imo.

**Comment by lrmtheboss** [comment]
I don't see an event for when the guis have been reloaded so that plugins can add their guis back afterward since the reload method clears the GUI hashmap by creating a new hashmap
In the GUIManager class, I don't see a way to add a GUI built from the GUIBuilder class

**Comment by lrmtheboss** [comment]
Much clearer now, but it seems it won't work for what I need

Thanks anyway

**Comment by haloflooder** [comment]
If you don't mind me asking. what were you trying to achieve?

**Comment by lrmtheboss** [comment]
I was coding a plugin that was to have a GUI to change each player's settings and I was thinking if I could use dynamicgui to deal with all the GUI-related stuff, it would save me from having to deal with it all manually. I've got it all sorted w/o dynamicgui for now
