### ISSUE TITLE
Custom replacers

### ISSUE THREAD

**Issue by virustotalop** [ClubObsidian/DynamicGui#9]
Allow users to define custom replacers for messages etc

**Comment by haloflooder** [comment]
Maybe also add an ability to set temporary variables via functions that the configurator can use to make more advanced gui's.

```
functions:
- "tempvarset: varName;value"
- "tempvarequals: varName;value"
```

**Comment by virustotalop** [comment]
Part of #59

**Comment by virustotalop** [comment]
Implemented as macros in 4.x.
